apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
  - image: dreg:5000/cluster-mariadb-std:latest
    name: mysql
    env:
    - name: DB_DUMP_FILE
      # ENV OPT FOR DB TYPE
      value: default
    #- name: lb
    #  value: 10.10.64.242
    ports:
    - containerPort: 3306
      name: mysql
    #volumeMounts:
    # name must match the volume name below
    #- name: mysql-storage
      # mount path within the container
    #  mountPath: /var/lib/mysql
  #volumes:
  #- name: mysql-storage
  #  emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mysql
  name: mysql
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 3306
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: mysql
